// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 615);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("calendar.list.sortOrder", "f32b8d53-b8d5-4ae6-b90b-9a9689da3441");
user_pref("calendar.registry.f32b8d53-b8d5-4ae6-b90b-9a9689da3441.calendar-main-in-composite", true);
user_pref("calendar.registry.f32b8d53-b8d5-4ae6-b90b-9a9689da3441.disabled", true);
user_pref("calendar.registry.f32b8d53-b8d5-4ae6-b90b-9a9689da3441.name", "Home");
user_pref("calendar.registry.f32b8d53-b8d5-4ae6-b90b-9a9689da3441.type", "storage");
user_pref("calendar.registry.f32b8d53-b8d5-4ae6-b90b-9a9689da3441.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Seoul");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1626695834664");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.11.0");
user_pref("extensions.lastPlatformVersion", "78.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"02b9ab76-8f6b-4223-b504-d6ad957cb940\",\"default-theme@mozilla.org\":\"c097e45e-8bb7-4af2-a1b4-6763241c5aea\",\"google@search.mozilla.org\":\"03da6f0a-2680-4139-9c0f-14b79f6c90b9\",\"amazondotcom@search.mozilla.org\":\"d54a1009-5e9b-417c-86ac-aadca12cd1be\",\"bing@search.mozilla.org\":\"349ceff5-b7fe-4500-b635-9eb2418fe7b5\",\"ddg@search.mozilla.org\":\"931fb750-870a-46d4-ac97-9183b25dc494\",\"wikipedia@search.mozilla.org\":\"ebb40ac4-92b0-45e2-8198-7c926b048a24\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "56c28d94-bd00-488b-b395-64ae373bbc7");
user_pref("mailnews.filters.migration78", true);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "78.11.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "e7b370dd-0af3-4426-b372-b2342b661f32");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "5f9eb1ba-37d6-40b7-bafb-346b949b1db9");
user_pref("toolkit.telemetry.previousBuildID", "20210528153351");
